apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks-staging
  region: ap-southeast-2
  version: "1.18"
managedNodeGroups:
- name: primary-1-18
  instanceType: t3.medium
  minSize: 3
  maxSize: 6
  spot: true
