apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks-calico-tigera
  region: ap-southeast-2
  version: "1.20"
managedNodeGroups:
- name: nix-t3-large
  instanceType: t3.large
  minSize: 3
  maxSize: 6
  spot: true
cloudWatch:
  clusterLogging:
    enableTypes: ["*"]