--- 
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: config-file
  region: ap-southeast-2

nodeGroups:
  - name: ng-default
    instanceType: t3.medium
    desiredCapacity: 2
