--- 
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eksctl-test
  region: ap-southeast-2

nodeGroups:
  - name: ng1-public
    instanceType: t3.medium
    desiredCapacity: 2
  
managedNodeGroups:
  - name: ng2-managed
    instanceType: t3.medium
    minSize: 1
    maxSize: 3
    desiredCapacity: 2  